[tool.bumpversion]
allow-dirty = true
commit = true
config-file = "pyproject.toml"
current_version = "0.3.1"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
replace = "{new_version}"
search = "{current_version}"
serialize = [
    "{major}.{minor}.{patch}",
]
tag = false

[[tool.bumpversion.files]]
allow-dirty = true
filename = "CHANGELOG.md"
replace = """## [Unreleased]

## [{new_version}] - {now:%Y-%m-%d}
"""
search = """## [Unreleased]
"""
